-- Notification system (P1) — outbound webhooks per project.
-- Manual migration; not generated by drizzle-kit. Apply locally via
--   pnpm exec wrangler d1 migrations apply wana-control-plane --local
-- and on prod via
--   pnpm exec wrangler d1 execute wana-control-plane --remote
--     --file=packages/schema/migrations/0001_notifications.sql
-- (the remote D1 does not have a `d1_migrations` tracking row — see
--  memory/deploy-notes.md for the historical reason).

CREATE TABLE notification_endpoints (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'webhook',           -- 'webhook' only in P1
  target TEXT NOT NULL,                            -- https:// only
  secret_enc TEXT NOT NULL,                        -- AES-GCM ciphertext, base64
  secret_nonce TEXT NOT NULL,                      -- AES-GCM nonce, base64
  secret_hint TEXT NOT NULL,                       -- last 4 chars of raw secret (for UI)
  kek_version INTEGER NOT NULL DEFAULT 1,          -- which WEBHOOK_KEK_Vx was used
  config_json TEXT,                                -- channel-specific config (P2)
  is_active INTEGER NOT NULL DEFAULT 1,
  consecutive_failures INTEGER NOT NULL DEFAULT 0, -- P2 auto-deactivate
  created_at INTEGER NOT NULL,
  created_by_user_id TEXT
);
CREATE INDEX idx_notif_ep_project ON notification_endpoints(project_id);

CREATE TABLE notification_rules (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  endpoint_id TEXT NOT NULL REFERENCES notification_endpoints(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  on_issue_created INTEGER NOT NULL DEFAULT 0,     -- P1
  on_issue_resolved INTEGER NOT NULL DEFAULT 0,    -- P2
  on_issue_regressed INTEGER NOT NULL DEFAULT 0,   -- P2
  on_spike INTEGER NOT NULL DEFAULT 0,             -- P3
  filter_query TEXT,                               -- search-query grammar; null = no filter
  min_interval_seconds INTEGER NOT NULL DEFAULT 60,
  last_fired_at INTEGER,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  created_by_user_id TEXT
);
CREATE INDEX idx_notif_rule_project ON notification_rules(project_id);
CREATE INDEX idx_notif_rule_endpoint ON notification_rules(endpoint_id);
CREATE INDEX idx_notif_rule_project_active ON notification_rules(project_id, is_active);

-- FKs use ON DELETE SET NULL so deleting an endpoint/rule does NOT erase
-- audit history; deliveries survive with their rule/endpoint id nulled out.
CREATE TABLE notification_deliveries (
  id TEXT PRIMARY KEY,
  rule_id TEXT REFERENCES notification_rules(id) ON DELETE SET NULL,
  endpoint_id TEXT REFERENCES notification_endpoints(id) ON DELETE SET NULL,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  issue_id TEXT,
  event_kind TEXT NOT NULL,                        -- 'issue.created' | 'test' in P1
  status TEXT NOT NULL,                            -- 'delivered' | 'failed' | 'rejected'
  attempt INTEGER NOT NULL DEFAULT 1,
  response_status INTEGER,
  response_ms INTEGER,
  error_message TEXT,
  payload_preview TEXT,                            -- first 1024 chars of request body
  created_at INTEGER NOT NULL,
  delivered_at INTEGER
);
CREATE INDEX idx_notif_del_project_created ON notification_deliveries(project_id, created_at DESC);
